### ISSUE TITLE
Error transaction failed: you cannot unilaterally unverify another creator

### ISSUE THREAD

**Issue by solstealer** [sonar-watch/nft-creator-ui#2]
hello everyone trying to mint my first nft through sonar but myself and several other users are just getting the error message 
" Error transaction failed: you cannot unilaterally unverify another creator "
anyone with experience or advice?

**Comment by olivbau** [comment]
I just created an NFT without problem
Do you do it on the site directly : https://nft-creator.sonar.watch/#/
Or locally with the repo?
